
CREATE TABLE "SYSTEM"."PHONENUMBER_INFO" 
   (	"PHONENUMBER" NUMBER(10,0) NOT NULL ENABLE, 
	"NUMBERTYPE" VARCHAR2(15 BYTE), 
	"PROVIDER" VARCHAR2(20 BYTE), 
	"UNID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PHONENUMBER_INFO_PK" PRIMARY KEY ("PHONENUMBER"),
	 CONSTRAINT "PHONENUMBER_INFO_FK1" FOREIGN KEY ("UNID")  REFERENCES "SYSTEM"."USER_INFO" ("USERID") ENABLE)
	 

	 CREATE TABLE "SYSTEM"."USER_INFO" 
   (	"USERID" NUMBER(10,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(20 BYTE), 
	"ADDRS" VARCHAR2(20 BYTE), 
	 CONSTRAINT "USER_INFO_PK" PRIMARY KEY ("USERID"))
	 